[package]
name = "tetris"
version = "0.1.1"
authors = ["Mr.Robb <rob.ariosa@hotmail.com>"]
description = "ğŸ•¹ï¸ Cross-platform Tetris environment made with Rust."
edition = "2018"

[dependencies]
ggez = "0.5.1"
na = "0.18.3"
rand = "0.7.3"
leg = "1.0.0"

[package.metadata.bundle]
name = "Tetris"
identifier = "com.mrrobb.tetrisrs"
icon = [".assets/icon.png"]
version = "0.1.0"
resources = [".assets"]
copyright = "Copyright (c) Roberto Ariosa 2019. All rights reserved."
category = "Developer Tool"
short_description = "Tetris Environment"
long_description = """ğŸ•¹ï¸ Cross-platform Tetris environment made with Rust."""
deb_depends = []
osx_frameworks = []
